[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 8080
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "10.2.4"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co https://cdn.brevo.com https://sibautomation.com;"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/javascript"
