
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co https://cdn.brevo.com https://sibautomation.com;"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/javascript"

# Handle SPA routing - updated with higher priority
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20", NPM_VERSION = "10" }

[build.processing]
  skip_processing = false

[build.processing.js]
  bundle = false
  minify = false
